name: Upload Configs

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Filename to upload'
        required: true
      file_content:
        description: 'File content'
        required: true

jobs:
  upload-config:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Configure Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    
    - name: Create or Update Config File
      env:
        FILENAME: ${{ github.event.inputs.filename }}
        FILE_CONTENT: ${{ github.event.inputs.file_content }}
      run: |
        mkdir -p Configs
        echo "$FILE_CONTENT" > "Configs/$FILENAME"
        
        git add "Configs/$FILENAME"
        git commit -m "Add/Update config file: $FILENAME"
        git push
